
package ua.nure.location.server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Places", targetNamespace = "http://location.nure.ua/server/service", wsdlLocation = "http://localhost:9000/places?wsdl")
public class Places
    extends Service
{

    private final static URL PLACES_WSDL_LOCATION;
    private final static WebServiceException PLACES_EXCEPTION;
    private final static QName PLACES_QNAME = new QName("http://location.nure.ua/server/service", "Places");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/places?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLACES_WSDL_LOCATION = url;
        PLACES_EXCEPTION = e;
    }

    public Places() {
        super(__getWsdlLocation(), PLACES_QNAME);
    }

    public Places(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLACES_QNAME, features);
    }

    public Places(URL wsdlLocation) {
        super(wsdlLocation, PLACES_QNAME);
    }

    public Places(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLACES_QNAME, features);
    }

    public Places(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Places(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlaceService
     */
    @WebEndpoint(name = "PlacePort")
    public PlaceService getPlacePort() {
        return super.getPort(new QName("http://location.nure.ua/server/service", "PlacePort"), PlaceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlaceService
     */
    @WebEndpoint(name = "PlacePort")
    public PlaceService getPlacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://location.nure.ua/server/service", "PlacePort"), PlaceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLACES_EXCEPTION!= null) {
            throw PLACES_EXCEPTION;
        }
        return PLACES_WSDL_LOCATION;
    }

}
